name: Run Vehicle Auction Scraper

on:
  schedule:
    - cron: "0 */24 * * *"  # Runs every 24 hours
  workflow_dispatch:  # Allows manual execution

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Chrome & WebDriver for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Auction Scraper
        run: python auction_scraper.py

      - name: List Directory Contents (Debugging)
        run: ls -lah

      - name: Check If CSV Exists Before Uploading
        run: |
          if [ -f "auction_results.csv" ]; then
            echo "✅ CSV file found."
          else
            echo "❌ ERROR: CSV file is missing!"
            exit 1
          fi

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: auction-results
          path: ./auction_results.csv
