name: Run Vehicle Auction Scraper

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Auction Scraper
        run: python auction_scraper.py

      - name: Upload CSV as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: auction-results
          path: auction_results.csv
